### ISSUE TITLE
Reset globals when code changes

### ISSUE THREAD

**Issue by atesgoral** [lionleaf/dwitter#357] opened 2018-06-30 15:14 UTC
Would be nice to find a way to either sandbox the global scope or to actively delete globals introduced by the dweet, so that globals that were present in a previous iteration of the code do not leak into the current global scope.

This often causes broken dweets to be posted because the author doesn't realize some magical variable they're still taking advantage of no longer exists. Or the common case of capturing mouse position in a new global, but making the mistake of using the global in the very first frame while it's still undefined.

**Comment by lionleaf** [comment] 2018-06-30 17:17
I very much agree. It's the main cause for broken dweets at the moment. This is a duplicate of #93 though, so closing this.

Any thoughts on how to do this in a way that's snappy enough for the live edits?

**Closed by lionleaf** 2018-06-30 17:17 UTC
