### ISSUE TITLE
Comment parser chokes on anchors in urls

### ISSUE THREAD

**Issue by yonatan** [lionleaf/dwitter#420] opened 2018-10-25 17:46 UTC
See comments on https://www.dwitter.net/d/2667

**Comment by lionleaf** [comment] 2018-10-26 01:54
Yep :| Duplicate of #334 which has more examples. It looks like there are two issues found so far: anchors in urls and # symbols in code blocks.

Closing this so we can move discussion to #334 :)

**Closed by lionleaf** 2018-10-26 01:54 UTC
