### ISSUE TITLE
shorten more stuff than just Math.sin, Math.cos, Math.tan, rgba

### ISSUE THREAD

**Issue by greggman** [lionleaf/dwitter#115] opened 2017-02-25 02:32 UTC
Of course it's amazing what people are already doing in 140 characters but you added R,S,C,T etc how about shortening all the canvas functions and properties as well as in

```
Object.defineProperties(x,{
  goc: { set: (v) => { x.globalCompositeOperation = v; }, },
  fs: { set: (v) => { x.fillStyle = v; }, },
  ss: { set: (v) => { x.strokeStyle = v; }, },
  ga: { set: (v) => { x.globalAlpha = v; }, },
  lw: { set: (v) => { x.lineWidth = v; }, },
  w: { set: (v) => { x.width = v; }, },
  h: { set: (v) => { x.height = v; }, },
});

x.fr = x.fillRect.bind(x);
x.sr = x.strokeRect.bind(x);
x.bp = x.beginPath.bind(x);
x.cp = x.closePath.bind(x);
x.f = x.fill.bind(x);
x.s = x.stroke.bind(x);
x.t = x.translate.bind(x);
x.r = x.rotate.bind(x);
x.sc = x.scale.bind(x);
x.sv = x.save.bind(x);
x.rs = x.restore.bind(x);
x.st = x.setTransform.bind(x);
x.sr = x.strokeRect.bind(x);
```

etc...

Or you could take it even further and remove the `x.` with

```
const FR = x.fillRect.bind(x);
const SR = x.strokeRect.bind(x);
const BP = x.beginPath.bind(x);
const CP = x.closePath.bind(x);
const F = x.fill.bind(x);
const ST = x.stroke.bind(x);
const TR = x.translate.bind(x);
const RT = x.rotate.bind(x);
const SC = x.scale.bind(x);
const SV = x.save.bind(x);
const RS = x.restore.bind(x);
```

Also a how about 

```
var H = function(h,s,l,a) {
    a = a === undefined ? 1 : a;
    return "hsla("+(h)+","+(s)+","+(l)+","+a+")";
};
```

**Comment by lionleaf** [comment] 2017-02-25 13:31
While this would make it possible to create more advanced dweets, the end result would be even less readable, harder to get into and the end result would just be the same as increasing the character count. I've decided that I was to keep it as simple as possible.

This issue is a duplicate of #95, see discussion there. Closing this one

**Closed by lionleaf** 2017-02-25 13:31 UTC
