### ISSUE TITLE
fullscreen for sample dweet

### ISSUE THREAD

**Issue by gabrielsroka** [lionleaf/dwitter#164] opened 2017-03-05 01:41 UTC
the sample dweet (at the top of the page) doesn't look like other dweets:
1. not fullscreen
2. it's black on white instead of white on black

btw, i like black on white better -- can we have it back? at least as an option?

thanks,

**Comment by lionleaf** [comment] 2018-08-06 01:34
Duplicate of #157

**Closed by lionleaf** 2018-08-06 01:34 UTC
