### ISSUE TITLE
some dweets work in preview but not when you dweet them

### ISSUE THREAD

**Issue by donbright** [lionleaf/dwitter#131] opened 2017-02-27 00:02 UTC
example

`x.font='525px A',x.fillStyle='#'+'09F911,029D74,E35BD8,4156C5,635688,fff'.split(',')[i],x.fillText(i>4?'+C0':'█',i<5?i*384:770,684);i=~~t%6
`

i wonder if this accounts for a lot of the 'blank dweets' i see in 'new' (i know some are firefox vs chrome issues but ...)

**Comment by lionleaf** [comment] 2017-02-27 00:25
This is a result of the #93 bug. You are using the variable 'i' in the code, which is undefined
<img width="453" alt="screenshot 2017-02-27 00 21 13" src="https://cloud.githubusercontent.com/assets/610925/23345249/ee99d6c0-fc82-11e6-8a67-23e737b4d476.png">


It works in the preview because i is defined by the example-dweet that's loaded to begin with.

Is there an easy/cheap way to reset the whole js scope within the iframe? We'd want to remove any global variables as well as anyone attached to c, x etc.

**Comment by sigvef** [comment] 2017-02-27 01:24
One approach is to replace the entire iframe with a new one.

**Comment by donbright** [comment] 2017-02-27 01:26
oh thank you for looking in to this. i fixed my dweet. i also fixed my posted text above so it wasnt escaped!! `~` should have been `~~`

**Comment by gabrielsroka** [comment] 2017-03-05 01:40
would it help if the sample dweet used `var i` instead of `i` ?

**Comment by gabrielsroka** [comment] 2017-03-19 17:04
i tried changing it from `i` (which declares a global variable) to `var i` (which declares a function level variable), and it seems to work better. @lionleaf, your thoughts?

**Comment by lionleaf** [comment] 2018-01-19 06:56
Closing as a duplicate of #93

**Closed by lionleaf** 2018-01-19 06:56 UTC
